twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        poster_public_path: '%poster_public_path%'

when@test:
    twig:
        strict_variables: true
